name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * 1' # every monday at 3am
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: videah
          base: master
          head: master
